### ISSUE TITLE
sqlTypes 大小写问题

### ISSUE THREAD

**Issue by WhoIsSmile** [bookong/zest-example#7]
#put 进去的时候是全小写
 this.getSqlTypes().put(StringUtils.lowerCase(rs.getString("column_name")), rs.getInt("data_type"));

#使用的时候不区分大小写
Integer sqlType = (Integer)sqlTypes.get(columnName);
如果数据库字段有大小写存在（驼峰命名）存在bug

**Comment by bookong** [comment]
真是让我受宠若惊，竟然还真有人关注了我写的东西。不知道是我的熟人吗？
你说的这个问题，当时我是遇到一个什么问题才改成小写的有些记不清了。最近重心没在这个上面，我有空儿看一下。
